# Codecov configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    # Overall project coverage
    project:
      default:
        # Compare coverage to base commit (auto)
        target: auto
        # Allow up to 0.5% decrease in coverage
        # This prevents PRs from significantly reducing coverage
        threshold: 0.5%
        # Don't fail if coverage stays the same or increases
        if_ci_failed: error

    # Coverage for changed code in PR
    patch:
      default:
        # Require new code to have reasonable coverage
        target: 10%
        # Allow some flexibility for small changes
        threshold: 0%
        if_ci_failed: error

  # Precision for coverage percentages
  precision: 2
  round: down

# Pull request comments
comment:
  # Post coverage report as PR comment
  layout: "header, diff, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Ignore patterns (if needed in future)
ignore:
  - "tests/**/*"
  - "**/__pycache__/**/*"
